### ISSUE TITLE
Data not copied over

### ISSUE THREAD

**Issue by popey** [snapcrafters/signal-desktop#1]
Copied over from https://github.com/signalapp/Signal-Desktop/issues/1798#issuecomment-425043954

" I am having some trouble with this snap package. On my system, I have to use the --classic switch because otherwise the app will fail to start. So I have ~/snap/signal-desktop and within that, there's a folder "83" and a folder "90". Back when I installed it, it was only "83" there and within that folder, the app created a .config/Signal directory to store the settings and messages.
But after the app got updated and the "90" folder appeared, the .config/Signal directory was not copied over to the "90" folder. I had to manually do this in order for the updated version to access the saved conversations. I assume I will need to do this again once Signal gets updated the next time."

**Comment by galgalesh** [comment]
Closing this as it's a known issue with Snapd. This response contains a workaround:

https://github.com/snapcrafters/signal-desktop/issues/8#issuecomment-607279119
