### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by hazedine** [snapcrafters/signal-desktop#11]
Hi, any estimate on the release of the source code?

**Comment by scadu** [comment]
@popey @flexiondotorg would it be possible to provide some sources? README has been changed almost a year ago and sharing more details regarding this issue would be much appreciate (I would be even more happy with using Snap :unicorn:).

**Comment by popey** [comment]
Sorry, I missed this issue. The snap is built from the upstream source largely unmodified. We just run the sequence of steps that's required to build it and push that to the store. The only change (not to the application source) is to the package.json to ensure the application launches with support for app indicators correctly.  We just clone the source, spawn a lxc container and build it there, then push to the store. 

What's probably useful would be if I dropped a `.travis.yml` in this repo which automates the build in public, so you can have more confidence we're building it correctly, and not messing with the upstream source. I'll get that done this week.

**Comment by galgalesh** [comment]
@popey any update on the `.travis.yml` file?

**Comment by popey** [comment]
Turned out to be harder than I thought. I'll get to it.

**Comment by IUSR** [comment]
I've been building Signal desktop for use on my Arch laptop for a while (too lazy to check the AUR), it would be great to have a snap for my laptop at work, with the souce code that is. Thanks!

**Comment by galgalesh** [comment]
@popey you can close this issue since this repo now contains the `snapcraft.yaml` file.
