### ISSUE TITLE
Rendering issue in snap version of Signal Desktop v1.27.2

### ISSUE THREAD

**Issue by jayschwa** [snapcrafters/signal-desktop#12]
Upstream issue: https://github.com/signalapp/Signal-Desktop/issues/3574#issuecomment-529152706

A Signal developer said that the snap build needs its process updated.

**Comment by popey** [comment]
Thanks for the bug report. Looking into it.

**Comment by popey** [comment]
Sorry about this. The latest revision in the edge channel should have this fixed. Please could you or anyone else affected try `snap refresh signal-desktop --edge` and restart Signal Desktop, to see if the changes have worked. Once confirmed, I will release to the stable channel.

**Comment by jayschwa** [comment]
It seems like it's fixed. Thanks for the quick turnaround!

**Comment by popey** [comment]
Thanks so much for testing. This is now in the stable channel.
