### ISSUE TITLE
tray icon missing on Unity

### ISSUE THREAD

**Issue by pszi1ard** [snapcrafters/signal-desktop#15]
Since a recent update, the signal application tray icon went missing on Unity.

```
$ cat /etc/lsb-release  | tail -n 1
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

$ apt-cache show unity | grep -m 1 Version
Version: 7.5.0+18.04.20190304-0ubuntu1

$ snap list | grep signal 
signal-desktop                    1.31.0                      299   stable    snapcrafters      -
```

**Comment by Armag67** [comment]
Same for me since today on Manjaro Xfce:
```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	19.0.2
Codename:	Kyria

$ snap list | grep signal 
signal-desktop     1.32.0                      300   stable    snapcrafters  -
```

**Comment by w-sky** [comment]
Same with Ubuntu 19.10

snap list | grep -i signal
signal-desktop           1.32.1                      301   stable    snapcrafters      -

apt show unity
Package: unity
Version: 7.5.0+19.10.20190924-0ubuntu1

**Comment by Armag67** [comment]
> Same for me since today on Manjaro Xfce:
> 
> ```
> $ lsb_release -a
> LSB Version:	n/a
> Distributor ID:	ManjaroLinux
> Description:	Manjaro Linux
> Release:	19.0.2
> Codename:	Kyria
> 
> $ snap list | grep -i signal 
> signal-desktop     1.32.0                      300   stable    snapcrafters  -
> ```

Solved by installing `xfce4-statusnotifier-plugin` from AUR beside `Notification Area` in Xfce panel.

**Comment by pszi1ard** [comment]
I have `libappindicator3-1` installed, still no tray icon.
