### ISSUE TITLE
Wrong binary packaged on 32bit system

### ISSUE THREAD

**Issue by zdzichu** [snapcrafters/signal-desktop#16]
Starting snap fails:

`$ signal-desktop `
`/snap/signal-desktop/292/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/292/opt/Signal/signal-desktop: cannot execute binary file: Exec format error`
`/snap/signal-desktop/292/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/292/opt/Signal/signal-desktop: Success`

Looks like the file is built for x86_64:
`$ file /snap/signal-desktop/292/opt/Signal/signal-desktop`
`/snap/signal-desktop/292/opt/Signal/signal-desktop: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 3.2.0, BuildID[sha1]=cc24f25f5633f1b4ac1a156a7d84fc2e363bf4ee, stripped`

While this is a 32-bit system:

`$ hostnamectl`
`…`
`Operating System: Ubuntu 18.04.4 LTS`
`Kernel: Linux 4.15.0-88-generic`
`Architecture: x86`

`$ snap list signal-desktop`
`Name            Version  Rev  Tracking  Publisher     Notes`
`signal-desktop  1.30.0   292  edge      snapcrafters  -`

**Comment by popey** [comment]
Thanks for the report.
I have removed the 32-bit build. We only support the 64-bit intel architectures now.
