### ISSUE TITLE
[Enhancement]: ARM64 snap of Signal Desktop

### ISSUE THREAD

**Issue by bceverly** [snapcrafters/signal-desktop#178]
### What changes would you like?

Hi,

I just got a Lenovo Thinkpad X13S machine and I'd really love to have an ARM64 version of the Signal Desktop snap.  Anyone willing to give it a go?  I'd be happy to test it on my hardware!

Thanks,
Bryan :)

### Any extra information?

I'm on the official 23.10 (Mantic) build for the X13S hardware

**Comment by popey** [comment]
Thanks for the issue. This snap package re-packs the official upstream release. Currently, the upstream developers only publish an amd64 package, which we consume. We can only post one once they publish an arm64/aarch64 package. Of course, we could build our own, but it's preferable to consume the official upstream builds.

**Comment by jnsgruk** [comment]
Having a go at this here: #179. Keen to get any feedback!
