### ISSUE TITLE
Characters not rendered properly

### ISSUE THREAD

**Issue by karaal** [snapcrafters/signal-desktop#20]
## Bug Description

All characters in "choose file" window are rendered as boxes.

## Steps to Reproduce

1. Click "plus" button placed right to "Send a message" input

## Actual Result:

All characters (dir list, buttons, file names) are rendered as squares.

## Expected Result:

Proper (readable) text.

## Screenshots

![image](https://user-images.githubusercontent.com/8842882/76843929-d50dcf80-683c-11ea-8a57-1239aca1c8e2.png)

Platform Info

Signal Version:

1.32.1, installed via snapcraft

Operating System:

Fedora 31 64-bit

Linked Device Version:

Android 7.1.2
Link to Debug Log

https://raw.githubusercontent.com/matedu/logs/master/2020-03-14-signal.log

**Comment by popey** [comment]
Thanks for the report. Does this still happen with the latest build in the stable channel?

**Comment by matedu** [comment]
I refreshed snaps today, this bug still happen.

**Comment by matedu** [comment]
After snap refresh to 1.33 it's still a case.

**Comment by maqp** [comment]
Hi! Just to let you know the bug's still present with the 1.34.4 release and Fedora 32.

**Comment by davenicoll** [comment]
Still present in 1.36.1 snap on Ubuntu 20.04. FYI this issue has been observed in other snap packages, and resolved, see here: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365

**Comment by Victoremepunto** [comment]
I can also see the reported issue, none of the above suggested workaround fixes works for me, I tried removing everything from:
```
/var/cache/fontconfig/*
~/.cache/fontconfig/*
~/snap/signal-desktop/common/.cache/
```
and then `fc-cache -r` 

I am using Fedora 32, snap v1.37.2

**Comment by davenicoll** [comment]
> I can also see the reported issue, none of the above suggested workaround fixes works for me, I tried removing everything from:
> 
> ```
> /var/cache/fontconfig/*
> ~/.cache/fontconfig/*
> ~/snap/signal-desktop/common/.cache/
> ```
> 
> and then `fc-cache -r`
> 
> I am using Fedora 32, snap v1.37.2

Updated to snap v1.37.2 and it started happening again.

Re-ran 
``` shell
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```
and restarted Signal, and no more boxes. Any word from the signal devs, or are we going to have to do this for every update?

**Comment by hackel** [comment]
I just ran into this issue yet again, and it took me ages to figure out how to solve it, so I wanted to add _yet another_ directory to remove cached fontconfig files from:
`/var/snap/signal-desktop/common/fontconfig`
I guess this is used to give snaps access to local fonts on the host system or something.

**Comment by galgalesh** [comment]
Closing this issue as it's a generic issue with snaps. Please reopen the issue if you know a way to solve it in the snap itself.
