### ISSUE TITLE
[Bug]: GH Action erroneously suggests promoting incorrect releases

### ISSUE THREAD

**Issue by popey** [snapcrafters/signal-desktop#204]
### What happened?

In issue #201 - generated by a GH action (I believe) - the maintainers were told to promote revisions 34 and 35. These are not correct revisions. It should have suggested to promote 556 and 557.
As a result, if done without double-checking, the maintainers could (and did) easily promote an old, broken, insecure release. This shouldn't be allowed happen.

### What should have happened?

The action should have informed the maintainer to promote the correct revisions.

### Output of `snap info $snap_name`

```shell
Not relevant
```

### Output of `snap connections $snap_name`

```shell
Not relevant
```

### Output of `snap version`

```shell
Not relevant
```

**Comment by popey** [comment]
![image](https://github.com/snapcrafters/signal-desktop/assets/1841272/247431bc-e338-4850-84aa-a12babcb03dd)

![image](https://github.com/snapcrafters/signal-desktop/assets/1841272/eea5a578-0ca6-4bc1-80db-6d7c0945cb84)

**Comment by merlijn-sebrechts** [comment]
I see two issues

1. The examples part of the bot text shouldn't contain numbers
2. The bot should have some for of safeguard not to promote ancient versions

**Comment by merlijn-sebrechts** [comment]
This is fixed now, thanks to @jnsgruk's incredible efforts!
