### ISSUE TITLE
Update Signal Desktop icon, screenshots and description on the Snapcraft store

### ISSUE THREAD

**Issue by Cerberus0** [snapcrafters/signal-desktop#24]
I think it's time to update this app's [Snapcraft store listing](https://snapcraft.io/signal-desktop):

- [ ] Update the app's icon.
- [ ] Update screenshots. Something like [this](https://signal.org/assets/screenshots/download-desktop-mac-2b3294f1801ea725d705f17c6511cd60ee5c5c57664e485deb22f5810e7cdaa1.png) would give people a better idea of what to expect.
- [ ] Update the description based on new content on the Signal.org homepage. It might also be a good idea to copy what they've done on https://signal.org/download/ and mention that "to use the Signal desktop app, Signal must first be installed on your phone."

Something like this could work for the updated description:

>_To use the Signal desktop app, Signal must first be installed on your phone._
>
>Millions of people use Signal every day for free and instantaneous communication anywhere in the world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a growing set of new features that help you stay connected. Signal’s advanced privacy-preserving technology is always enabled, so you can focus on sharing the moments that matter with the people who matter to you. 
>
>Signal is an independent 501c3 nonprofit. The complete source code for the Signal clients and the Signal server is available on GitHub.
>
>This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
>
>[Contact Snapcrafters](https://github.com/snapcrafters/signal-desktop/issues)

**Comment by Cerberus0** [comment]
Moved to the Snapcraft forum: https://forum.snapcraft.io/t/update-signal-desktop-screenshots-and-description-on-the-snapcraft-store/16487

**Comment by Cerberus0** [comment]
Re-opened this here due to lack of activity on the Snapcraft forum.

**Comment by Cerberus0** [comment]
Seven months have past and this app's Snapcraft store listing still looks outdated. I would gladly update it myself, but I don't think that's possible.

The new icon files can be found here:

https://github.com/signalapp/Signal-Desktop/tree/development/images

**Comment by popey** [comment]
Sorry I missed this. Now done.
