### ISSUE TITLE
Old snaps are kept on disk

### ISSUE THREAD

**Issue by mimre25** [snapcrafters/signal-desktop#248]
### What changes would you like?

I'm trying to clean up my disk a bit and noticed that there are quite a lot of old versions of signal-desktop being kept on disk:

```sh
➜  ls -lah /var/lib/snapd/snaps | grep signal
-rw-------  1 root root 177M Sep 12 21:29 signal-desktop_517.snap
-rw-------  1 root root 174M Nov  6 21:56 signal-desktop_534.snap
-rw-------  1 root root 174M Nov 13 12:24 signal-desktop_536.snap
-rw-------  1 root root 174M Nov 15 18:52 signal-desktop_549.snap
-rw-------  1 root root 173M Nov 24 14:33 signal-desktop_556.snap
-rw-------  1 root root 173M Dez  7 17:44 signal-desktop_588.snap
-rw-------  1 root root 179M Dez 29 13:33 signal-desktop_592.snap
```

However, snap list only shows 6.42.1 (the one that is currently installed)

```sh
➜  snap list --all | grep signal
signal-desktop         6.42.1                      592    latest/stable    snapcrafters*  -
```

Are the old ones still necessary?

**Comment by jnsgruk** [comment]
Hi!

This is a snapd behaviour, and not related to this snap specifically. There is some more information in this thread that might help: https://superuser.com/questions/1310825/how-to-remove-old-version-of-installed-snaps
