### ISSUE TITLE
[Bug]: signal-desktop icon lost from ubuntu launcher and application launcher page after snap update - just black square showing

### ISSUE THREAD

**Issue by Jakethethird** [snapcrafters/signal-desktop#259]
### What happened?

After update (currently  latest/stable:    6.44.1 2024-01-18 (606) 191MB), the signal icon in launchers is lost - just an empty black square is shown in both launchers where the normal signal-desktop.png item should be visible. 
This is case on all 3 of my computers running ubuntu 22.04

### What should have happened?

- Signal icon should be shown in launcher menus, not just the name of the app.
- Temporary workaround: using "menu editor" program to edit signal-desktop desktop file, it shows no icon file is defined. I can manually select a signal-desktop.png file and it reappears, but is lost on further updates.

### Output of `snap info $snap_name`

```shell
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: today at 07:56 CET
channels:
  latest/stable:    6.44.1 2024-01-18 (606) 191MB -
  latest/candidate: 6.44.1 2024-01-18 (606) 191MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          6.44.1            (606) 191MB -
```

### Output of `snap connections $snap_name`

```shell
Interface               Plug                                   Slot                            Notes
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  :camera                         -
content[gnome-42-2204]  signal-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    :home                           -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
Interface               Plug                                   Slot                            Notes
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  :camera                         -
content[gnome-42-2204]  signal-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    :home                           -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     :x11                            -
```

**Comment by Jakethethird** [comment]
copy-paste error. Output of snap version:

snap    2.61.1
snapd   2.61.1
series  16
ubuntu  22.04
kernel  6.5.0-14-generic

**Comment by merlijn-sebrechts** [comment]
I cannot reproduce this. Can you show the filename of that `.desktop` file, and the contents?

**Comment by Jakethethird** [comment]
here you can see the desktop file and icon in the snap.

![20240119-11-04-35](https://github.com/snapcrafters/signal-desktop/assets/28954472/f389a33a-7fca-4ab4-8642-8f55c9c2e3a3)

`[Desktop Entry]
Name=Signal
Exec=signal-desktop --no-sandbox %U
Terminal=false
Type=Application
Icon=${SNAP}/meta/gui/signal-desktop.png
StartupWMClass=Signal
Comment=Private messaging from your desktop
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
Categories=Network;InstantMessaging;Chat;`


Here is the workaround that puts the icon back temporarily showing the path of the desktop that I edited.
![20240119-11-07-33](https://github.com/snapcrafters/signal-desktop/assets/28954472/facd661b-4dde-4069-a1e0-c407b1f8133a)

**Comment by Jakethethird** [comment]
When updating snaps (sudo snap refresh), generally the icons disappear transiently during the update, then reappear in the launchers at the end of the process. In the last updates of signal-desktop since 604 (last week), the icon disappears but does not come back again - just the black spaceholder with the name Signal. Logging out or rebooting makes no difference. No issue for other snaps, just this one.

**Comment by merlijn-sebrechts** [comment]
That's not the location that your menu bar should use, though. You menu bar should get it from `/var/lib/snapd/desktop/applications/`. Is the file in that directory correct?

**Comment by Jakethethird** [comment]
Hi, the desktop file edited by the menu editor program - which immediately changes the icons in the launchers, is:

`/var/lib/snapd/desktop/applications/signal-desktop_signal-desktop.desktop`

![2024-01-19_14-29](https://github.com/snapcrafters/signal-desktop/assets/28954472/89dc7223-9054-45ca-a9dd-a01786fdbcc9)

**Comment by merlijn-sebrechts** [comment]
@Jakethethird Can you show the contents of that file before it's edited by the menu editor program? This is what it looks like on my machine:

```
merlijn@idlab266:~$ cat /var/lib/snapd/desktop/applications/signal-desktop_signal-desktop.desktop
[Desktop Entry]
X-SnapInstanceName=signal-desktop
Name=Signal
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/signal-desktop_signal-desktop.desktop /snap/bin/signal-desktop --no-sandbox %U
Terminal=false
Type=Application
Icon=/snap/signal-desktop/606/meta/gui/signal-desktop.png
StartupWMClass=Signal
Comment=Private messaging from your desktop
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
Categories=Network;InstantMessaging;Chat;

```

This file is created by snapd during installation. It's normal that this is different from the one in the snap itself.

**Comment by merlijn-sebrechts** [comment]
What desktop environment are you using? Is it possible the desktop environment simply didn't refresh the icons after the update? And it refreshes the icons as soon as you open the menu editor?

**Comment by Jakethethird** [comment]
Your signal-desktop_signal-desktop.desktop file and mine are identical. 

Standard Gnome desktop on Ubuntu 22.04 LTS. I did wonder if it was not refreshing the icons also i.e. it is a Gnome-related issue rather than the snap. Logging out and in, plus rebooting didn't make a difference and this would normally refresh the icons.

If it is a common error, we'll soon hear. I don't want to waste your valuable time so perhaps close this and see if others report it?

**Comment by jnsgruk** [comment]
Indeed - I think this might be an oddity in your setup. I spent some time today trying to repro and haven't been able to, and there are no other reports.

You could try a `snap remove signal-desktop --purge` (making sure your messages are backed up!), then reinstall.
