### ISSUE TITLE
Create/Upload sticker pack does not work

### ISSUE THREAD

**Issue by mitaa** [snapcrafters/signal-desktop#26]
I have almost the same issue as https://github.com/signalapp/Signal-Desktop/issues/4165 with 1.33.1 installed through this snap on Fedora;
When I use the "Create/upload sticker pack" option I always get a new empty blue window accompanied by this error in the debug log (no errors in the developer tools console):

```code
ERROR 2020-04-16T18:22:29.279Z Preload error in [REDACTED]/app.asar/sticker-creator/preload.js:  ENOENT: no such file or directory, open '[REDACTED]/app.asar.unpacked/node_modules/sharp/package.json'
```

**Comment by mitaa** [comment]
Looking at
https://www.archlinux.org/packages/community/x86_64/signal-desktop/files/
it seems that there should be a folder called "app.asar.unpacked", apparently just for the "sharp" package which I guess is only used for the sticker creator.

It seems to be missing for me; I tried `sudo find / -type d -iname app.asar.unpacked` but nothing signal-desktop related turned up.

**Comment by josh-signal** [comment]
@mitaa is this different than #4165 or can I merge the issues?

**Comment by aibaraiduas** [comment]
Not sure if it is the same as [#4165](https://github.com/signalapp/Signal-Desktop/issues/4165), since I have the `app.asar.unpacked` folder in `/opt/Signal/resources`. Also, I only get a blue screen every other time I click to create a sticker (the 1st, 3rd, etc. clicks do not bring anything up at all). Maybe related?

**Comment by mitaa** [comment]
I think it may be an issue with the snap rather than signal-desktop itself.
I've tested this in a ubuntu vm and this issue doesn't occur for me with the official deb package there but does still with the snap.

Maybe this has to do with https://github.com/snapcrafters/signal-desktop/pull/23

**Comment by salim-b** [comment]
I can confirm the blue screen when trying to add an image to the sticker pack creator. But I get a different error message (`symbol lookup error`):

```
/snap/signal-desktop/320/opt/Signal/signal-desktop --type=renderer --no-sandbox --field-trial-handle=16041986219325698351,11103366893575689441,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=de --app-path=/snap/signal-desktop/320/opt/Signal/resources/app.asar --no-sandbox --no-zygote --native-window-open --preload=/snap/signal-desktop/320/opt/Signal/resources/app.asar/sticker-creator/preload.js --enable-remote-module --background-color=#3a76f0 --disable-electron-site-instance-overrides --num-raster-thread: symbol lookup error: /snap/signal-desktop/320/opt/Signal/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZN4vips6VImage15new_from_bufferEPKvmPKcPNS_7VOptionE
```

**Comment by salim-b** [comment]
This is still an issue with signal-desktop 1.34.1, rev 320. Is https://github.com/snapcrafters/signal-desktop/commit/cf8a1fd1c80fa8dfa97ce07afe07475cf8909e14 not included in rev 320?

**Comment by julian-alarcon** [comment]
I'm getting the same error with Ubuntu 20.04 and Signal 1.34.5, should I open a new case?
I got the blue screen after uploading 1 or any number of images.

`/snap/signal-desktop/345/opt/Signal/signal-desktop --type=renderer --no-sandbox --field-trial-handle=17677055450869877168,17176523047493136145,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=en-US --app-path=/snap/signal-desktop/345/opt/Signal/resources/app.asar --no-sandbox --no-zygote --native-window-open --preload=/snap/signal-desktop/345/opt/Signal/resources/app.asar/sticker-creator/preload.js --enable-remote-module --background-color=#3a76f0 --enable-spellcheck --enable-websql --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=7 --no-v8-untrusted-code-mitigations --shared-files=v8_snapshot_data:100: symbol lookup error: /snap/signal-desktop/345/opt/Signal/resources/app.asar.unpacked/node_modules/sharp/build/Release/sharp.node: undefined symbol: _ZN4vips6VImage15new_from_bufferEPKvmPKcPNS_7VOptionE`
