### ISSUE TITLE
launching armhf signal-desktop 1.30.0 crashes (Raspbian, Debian 10, Raspberry Pi 4)

### ISSUE THREAD

**Issue by esbeeb** [snapcrafters/signal-desktop#27]
Hello,
I installed the latest (32-bit) Raspbian, on a Raspberry Pi 4.  It's all updated.  Installed signal-desktop with:

`sudo snap install --edge signal-desktop`

Then I had to add the line:

`export PATH=$PATH:/snap/bin`

...to the end of my ~/.profile and reboot.

Then I could run the command "signal-desktop" from a command line.  **But it crashes**, never having appeared on the screen.  The error message looks like this:

> ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
> /snap/signal-desktop/297/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/297/opt/Signal/signal-desktop: cannot execute binary file: Exec format error
> /snap/signal-desktop/297/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/297/opt/Signal/signal-desktop: Success

That first line starting with "ERROR" is repeated many times.  Also near the start of the error output is this warning:

`/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)`

**Comment by matoken** [comment]
There is a similar problem in arm64 environment.
Probably amd64 binary is distributed.

install
```shell
$ snap search signal-desktop
Name            Version  Publisher     Notes  Summary
signal-desktop  1.30.0   snapcrafters  -      Signal Private Messenger for Windows, Mac, and Linux
$ sudo snap install --edge signal-desktop
```

run
```shell
$ /snap/bin/signal-desktop
/snap/signal-desktop/296/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/296/opt/Signal/signal-desktop: cannot execute binary f
ile: Exec format error
/snap/signal-desktop/296/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/296/opt/Signal/signal-desktop: Success
```
It is a binary of x86-64 (amd64).
```shell
$ file /snap/signal-desktop/296/opt/Signal/signal-desktop
/snap/signal-desktop/296/opt/Signal/signal-desktop: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib6
4/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=cc24f25f5633f1b4ac1a156a7d84fc2e363bf4ee, stripped
```

This is my environment.
```bash
$ snap info signal-desktop | tail
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     edge
refresh-date: yesterday at 16:26 JST
channels:
  stable:    --                            
  candidate: --                            
  beta:      --                            
  edge:      1.30.0 2020-01-24 (296) 131MB -
installed:   1.30.0            (296) 131MB -
$ snap version
snap    2.37.4-1+b1
snapd   2.37.4-1+b1
series  16
debian  10
kernel  5.4.28-sunxi64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ uname -a
Linux pinebook 5.4.28-sunxi64 #20.02.7 SMP Sat Mar 28 17:25:10 CET 2020 aarch64 GNU/Linux
```

**Comment by FatBirdie** [comment]
I get the same error as @matoken running on Pinebook Pro/Arm64

/snap/signal-desktop/296/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/296/opt/Signal/signal-desktop: cannot execute binary file: Exec format error
/snap/signal-desktop/296/snap/command-chain/desktop-launch: line 543: /snap/signal-desktop/296/opt/Signal/signal-desktop: Success

**Comment by ivr588** [comment]
Yes, I also get this issue. I went here:
https://snapcraft.io/install/signal-desktop/raspbian (scroll to the bottom) where there are instructions for installing signal-desktop with snap on raspabian under a subheading called "Enable snaps on Raspberry Pi and install Signal Desktop"

(it should not matter I'm not using raspabian I'm using rpi3 b+ with snaps:
  Operating System: Ubuntu 20.04 LTS
  Kernel: Linux 5.4.0-1012-raspi
  Architecture: arm64 )

it all installs fine; reboot then I get exactly the same error as @FatBirdie

**Comment by esbeeb** [comment]
Confusingly, there is a nice page on the Snapcraft website, suggesting that you'd get ARM64, what with the Raspberry Pi theming seen there: https://snapcraft.io/install/signal-desktop/raspbian

**Comment by esbeeb** [comment]
BTW: I started a thread on this in the Raspberry Pi forum as well: https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=290538

**Comment by esbeeb** [comment]
It's been over 6 months, and this is still a "New Issue", not even an officially acknowledged bug yet.

**Comment by esbeeb** [comment]
Reading this issue is recommended:
https://github.com/signalapp/Signal-Desktop/issues/3410

**Comment by galgalesh** [comment]
ARM64 build are not supported by this snap yet. I'm looking into why the store is still providing such builds.
