### ISSUE TITLE
Feature request: Verify upstream GPG signature

### ISSUE THREAD

**Issue by alexhaydock** [snapcrafters/signal-desktop#29]
Looking at the `Snapcraft.yaml` file, it doesn't look like there's any verification going on here for the fetched `.deb` file. For a security-focused application (or really any application) I think it would be a good idea if we verify the deb package as it gets pulled into the Snap build.

Does it make sense to include a `gpg --verify` step in the `override-build:` section?

Signing keys: https://updates.signal.org/desktop/apt/keys.asc

**Comment by alexhaydock** [comment]
Actually, doing this is a bit more complex than I thought so I [posted a forum thread here](https://forum.snapcraft.io/t/proposal-integrate-gpg-verification-for-upstream-deb-packages/16946) with some suggestions.

**Comment by jnsgruk** [comment]
Hi - this isn't really relevant anymore, since we're building the application from source, so you're able to check exactly what's being built. Closing for now, thank you!
