### ISSUE TITLE
Crash on initial start

### ISSUE THREAD

**Issue by lizthegrey** [snapcrafters/signal-desktop#42]
when invoked in the snap sandbox as `/snap/bin/signal-desktop`:

```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/330/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/lizf/snap/signal-desktop/330/.config/Signal
config/get: Did not find user config file, cache is now empty object
x-attr dependncy did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "sgnl"
No protocol specified
Segmentation fault (core dumped)
```

when invoked without sandboxing from `/snap/signal-desktop/330/opt/Signal/signal-desktop`:

```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/330/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/lizf/.config/Signal
config/get: Did not find user config file, cache is now empty object
x-attr dependncy did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
{"name":"log","hostname":"penguin","pid":2318,"level":30,"msg":"app ready","time":"2020-09-24T03:54:21.748Z","v":0}
{"name":"log","hostname":"penguin","pid":2318,"level":30,"msg":"starting version 1.36.1","time":"2020-09-24T03:54:21.751Z","v":0}
{"name":"log","hostname":"penguin","pid":2318,"level":30,"msg":"key/initialize: Generating new encryption key, since we did not find it on disk","time":"2020-09-24T03:54:21.800Z","v":0}
[...]
```
(and starts normally from there)

**Comment by basilfx** [comment]
I have the same problem, under Ubuntu 20.10 (installed signal-desktop 1.37.2 via Snapcraft).

```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/333/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/basilfx/snap/signal-desktop/333/.config/Signal
config/get: Did not find user config file, cache is now empty object
x-attr dependncy did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "sgnl"
[1]    9216 segmentation fault (core dumped)  snap run signal-desktop
```

**Comment by popey** [comment]
Having real difficulty reproducing this. Can someone who is getting this tell me if there's anything strange about your setup? wayland in use? Home directory mounted oddly? What's the output of `snap version` pls.
Also, 1.37.3 is now out and in the stable channel, which works fine here.

**Comment by basilfx** [comment]
Still the same problem with 1.37.3. I just use snap as installed by Ubuntu. As far as I know, I have not touched any of the Snap settings.

```
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/335/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/basilfx/snap/signal-desktop/335/.config/Signal
config/get: Did not find user config file, cache is now empty object
x-attr dependncy did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "sgnl"
[1]    384211 segmentation fault (core dumped)  snap run signal-desktop
```

`snap version`
```     
snap    2.47.1+20.10.1
snapd   2.47.1+20.10.1
series  16
ubuntu  20.10
kernel  5.8.0-25-generic
```

`lsb_release -a`

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

**Comment by pLuster** [comment]
Doesn't crash when running `/snap/signal-desktop/335/opt/Signal/signal-desktop` directly (starts in Xwayland) but crashes when running it properly with `/snap/bin/signal-desktop`.

**Comment by lizthegrey** [comment]
Just tried refreshing from 333 to 335, still same situation.

Additional detail about my setup: it is running inside an Ubuntu 20.04 VM within ChromeOS Crostini.

**Comment by renkun-ken** [comment]
Same here.

**Comment by isaiahfrantz** [comment]
same here, running on a fedora 33 VM though (was happening on my fedora 32 before os upgrade too)
signal-desktop worked fine before
```
❯ snap version 
snap    2.47.1-1.fc33
snapd   2.47.1-1.fc33
series  16
fedora  33
kernel  5.8.18-300.fc33.x86_64

~ 
❯ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

**Comment by deanso** [comment]
same problem here. Running on an freshly installed lenovo laptop with fedora 33.
installed with:
sudo dnf install snapd
sudo ln -s /var/lib/snapd/snap /snap
sudo snap install signal-desktop

error message in journalctl:
`nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: NODE_ENV production
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: NODE_CONFIG_DIR /snap/signal-desktop/335/opt/Signal/resources/app.asar/config
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: NODE_CONFIG {}
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: ALLOW_CONFIG_MUTATIONS undefined
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: HOSTNAME undefined
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: NODE_APP_INSTANCE undefined
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: SUPPRESS_NO_CONFIG_WARNING undefined
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: SIGNAL_ENABLE_HTTP undefined
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: userData: /home/neomash/snap/signal-desktop/335/.config/Signal
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: config/get: Did not find user config file, cache is now empty object
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: x-attr dependncy did not load successfully
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3358]: config/get: Did not find ephemeral config file, cache is now empty object
nov 12 23:59:38 fedora systemd[2381]: Started dbus-:1.2-io.snapcraft.Settings@0.service.
nov 12 23:59:38 fedora snap[3440]: 2020/11/12 23:59:38.822081 userd.go:98: Starting snap userd
nov 12 23:59:38 fedora signal-desktop_signal-desktop.desktop[3438]: Error org.freedesktop.DBus.Error.Failed: cannot find snap for connection: not supported
nov 12 23:59:38 fedora audit[3358]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=3358 comm="signal-desktop" exe="/snap/signal-desktop/335/opt/Signal/signal-desktop" sig=11 res=1
`

fedora:~$> snap version
snap    2.47.1-1.fc33
snapd   2.47.1-1.fc33
series  16
fedora  33
kernel  5.8.18-300.fc33.x86_64

**Comment by enrikb** [comment]
I saw the issue today on one machine recently upgraded to Ubuntu 20.10, using Wayland. Turned out that I had not enabled proposed updates on this machine and ran in a [known issue](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1897224). Updating `mutter` from proposed updates fixed the issue for me.

**Comment by galgalesh** [comment]
Anyone still seeing this issue in 2021? I can't reproduce it on Wayland either.

**Comment by galgalesh** [comment]
Please reopen the bug report if this is still happening.
