### ISSUE TITLE
Add plugs for camera and audio-record to Signal snap?

### ISSUE THREAD

**Issue by umasse** [snapcrafters/signal-desktop#44]
In the latest Signal desktop versions, you can now do audio and video calls. The list of connections in the snap does not show any interface for camera and audio recording.

This probably needs to change to make use of the new features.

**Comment by salimibrogimov** [comment]
Audio/video call freezes on Ubuntu 18.04, and I can't close the window or quit the app (so, I killed it).

**Comment by floscher** [comment]
Please reopen, video calls are not possible in version 5.0.0 when installed as snap. The app freezes as desribed in signalapp/Signal-Desktop#4523

**Comment by trevor87** [comment]
@floscher It seems there is a new ticket for this: https://github.com/snapcrafters/signal-desktop/issues/52
