### ISSUE TITLE
Missing font on tray icon menu

### ISSUE THREAD

**Issue by property-x** [snapcrafters/signal-desktop#51]
Moved from
https://github.com/signalapp/Signal-Desktop/issues/4956

## Problem to solve
Font on tray icon menu is not rendered.

## Steps to Reproduce
Install signal sudo snap install signal-desktop
start signal-desktop
right click on signal tray icon
Actual Result:

All rendered as "tofu" sign.

## Expected Result:

Text

## Screenshots
![image](https://user-images.githubusercontent.com/43217140/106258984-e70f1b80-621e-11eb-88e9-b414ae403126.png)

## Platform Info
Signal Version:

1.39.6

## Operating System:

OS: Manjaro Linux x86_64
Kernel: 5.10.7-3-MANJARO
Resolution: 1920x1080
WM: i3
Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
Icons: Papirus-Adapta-Nokto-Maia [GTK2/3]

## Link to Debug Log
https://debuglogs.org/bc99c8f90f59551b3a6026a2708eaf5598ba6dca3bed1024263eba854a40bf07

**Comment by liyakun** [comment]
is it as well related to https://forum.snapcraft.io/t/call-for-testing-signal-desktop/4865/28 ? thanks.

**Comment by galgalesh** [comment]
Is all text in the app these squares or only the text in the tray?

**Comment by marc0der** [comment]
I'm still seeing this issue. Has there been a resolution yet?

@galgalesh I only see this in the tray fonts, not the app itself.

**Comment by merlijn-sebrechts** [comment]
Can you test again with the latest version? We recently switched to core22 base.

**Comment by merlijn-sebrechts** [comment]
Closing this as it should be fixed in the latest version. Please reopen if the issue still persists!
