### ISSUE TITLE
 Incoming call rings, but application freezes

### ISSUE THREAD

**Issue by O-Gopal** [snapcrafters/signal-desktop#52]
When a call comes in, Signal rings, I see the icon of the caller, and I see a button by which to answer. When I press the answer button, I get what seems a normal full-screen display, with three buttons--"video," "camera," and "hang up." But although the ring keeps ringing, the Signal Desktop application freezes. The only way out seems to be to kill the application process.

Issue detailed on Signal's Github bug-tracking page:

https://github.com/signalapp/Signal-Desktop/issues/5009

Almost certainly a Snap issue.

**Comment by 3ter** [comment]
I'm getting the same app hangup when initiating a (video)call.

**Comment by galgalesh** [comment]
By default, signal does not have permission to access the Webcam and to your microphone. If the snap doesn't have these permissions, it will freeze when picking up a call.

You can fix this by running

```bash
snap connect signal-desktop:camera
snap connect signal-desktop:audio-record
```

You can also do this using the "Permissions" page in the Signal app page in the Snap Store on your computer.

We're in the process of requesting these permissions by default. After that, this should be fixed even without the workaround.

**Comment by galgalesh** [comment]
Please let us know if you still have the freeze even with these permissions enabled.

**Comment by galgalesh** [comment]
Note the progress of the permission request is tracked here: https://github.com/snapcrafters/signal-desktop/issues/55
