### ISSUE TITLE
signal-snap on latest/stable segfaults

### ISSUE THREAD

**Issue by Kedstar99** [snapcrafters/signal-desktop#54]
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/354/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/kd913/snap/signal-desktop/354/.config/Signal
config/get: Did not find user config file, cache is now empty object
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
x-attr dependency did not load successfully
config/get: Did not find ephemeral config file, cache is now empty object
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"
Invalid MIT-MAGIC-COOKIE-1 keySegmentation fault (core dumped)

This is on Ubuntu 21.04

**Comment by crtxcr** [comment]
@Kedstar99 Did you solve this? If so, what was the solution? I might be affected by something similiar.

**Comment by Kedstar99** [comment]
This was an issue where X11 somehow crashed on my machine. Hence anything that was running via xwayland wouldn't work, but stuff via wayland did.

My solution at the time was simply rebooting and everything seemed to work again.
