### ISSUE TITLE
Logitech webcam (video feed) is not working

### ISSUE THREAD

**Issue by fugenkleber** [snapcrafters/signal-desktop#55]
I tried to use one of my webcams on the laptop (one built-in; one via USB by Logitech), but neither is recognized by Signal. This problem only occurs if I use the snap version. The strange thing is, that the built-in microphone in the webcam is recognized by Signal.
Installing and using the Signal version directly from the Signal webpage following the "Linux (Debian-based) Install Instructions" works flawless. Therefore I believe, that the snap version is missing some permissions to access the webcams.

I'm using Xubuntu 21.04 (64-bit) on a Sony Vaio Laptop with an Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz.
USB webcam: Logitech Streamcam

**Comment by galgalesh** [comment]
For reference: https://forum.snapcraft.io/t/auto-connections-request-of-camera-and-audio-record-to-signal-desktop/24891

**Comment by galgalesh** [comment]
Auto-connection has been granted, this is now fixed.
