### ISSUE TITLE
signal-desktop is causing a kernel trap and crash

### ISSUE THREAD

**Issue by Kedstar99** [snapcrafters/signal-desktop#56]
I am using Kubuntu 21.04 with a Ryzen 5 3600, AMD Rx6800 and 32GB of RAM. 
Kernel 5.11.0-18 with lockdown mode strict

I am getting some kernel crashes when my pc is put to sleep and resumed. Specifically from signal.

```
12396   │ Jun  8 22:39:10 anon-desktop kernel: [  654.876223] audit: type=1400 audit(1623188350.897:173): apparmor="DENIED" operation="capable" profile="/snap/snapd/12057/usr/lib/snapd/snap-confine" pid=8641 comm="snap-confine" capability=4  capname="fsetid"
12397   │ Jun  8 22:39:12 anon-desktop kernel: [  656.924117] traps: signal-desktop[8641] trap int3 ip:55d640a66c58 sp:7ffdf67a32a0 error:0 in signal-desktop[55d640837000+626c000]
12398   │ Jun  8 22:39:29 anon-desktop kernel: [  673.515389] traps: signal-desktop[8762] trap int3 ip:55880a3a6c58 sp:7fffc80deaa0 error:0 in signal-desktop[55880a177000+626c000]

```
This is in my kern.log just before the crash.

**Comment by Kedstar99** [comment]
Reading on the forums, it may be caused by snapd. Trying snapd version 2.51 to see if that fixes the problem. Will report back if ti does.

**Comment by Kedstar99** [comment]
I haven't encountered the problem if signal wasn't opened. I have seen this issue twice when signal-desktop is opened but in a minimized state. I can't quite reproduce this precisely, it seems to occur only when I am a long time away from the computer. It may be something to do with a notification/new message and signal-desktop changing state maybe??

 I do sometimes also see my entire wayland session crash so it could be related to that.

It could also be a kernel bug.

**Comment by galgalesh** [comment]
Is it possible you get this when you get a call?

You can try to manually add the right permissions for video calling and seeing if it keeps happening:

```
snap connect signal-desktop:camera
snap connect signal-desktop:audio-record
```

(we're currently requesting these permissions be granted automatically to signal)

If it keeps happening, can you show more logs. Specifically kernel and apparmor logs might help here.

Finally, traps sometimes happen because of bad disks. Might be good to check the SMART info of your disk to make sure it isn't failing.

**Comment by Kedstar99** [comment]
I haven't seen this again so I'll assume it was fixed by a new kernel or new snapd.
