### ISSUE TITLE
Faster adoption of new signal releases

### ISSUE THREAD

**Issue by q-wertz** [snapcrafters/signal-desktop#58]
Hello,

it would be nice if the snap stays more up to date to the newest signal release. 
Currently the latest stable snap version is 5.7.1 (which is was released on june 30), newest  official one is 5.12.2 from today.
```
channels:
  latest/stable:    5.7.1  2021-07-06 (365) 174MB -
  latest/candidate: ↑                             
  latest/beta:      ↑                             
  latest/edge:      5.11.0 2021-07-31 (367) 174MB -
installed:          5.7.1             (365) 174MB -
```

Is this a process that can be automated or a manual one? If manual is there a way one can contribute?

**Comment by galgalesh** [comment]
The current process is the following:

1. When a new upstream release happens, I need to press the "trigger new build" button on snapcraft.io.
2. When that build is finished; it ends up in the `edge` channel. This build needs to be tested.
3. When it's tested, I need to manually publish it to the `stable` channel.

You can definitely help with step 2. Then I need a way to notify you, however. Maybe the best way to do this is using the Forum? Do you have an account on https://forum.snapcraft.io? Then I can ping you there every time there is a new release to help test it.

**Comment by q-wertz** [comment]
Would be happy to help :+1: I'm already on the snapcraft forum: `q-wertz`.

I'm already on the edge channel, no issues so far with `latest/edge:      5.11.0 2021-07-31 (367) 174MB -`

**Comment by galgalesh** [comment]
I started this thread on the forum for quick testing: https://forum.snapcraft.io/t/testing-signal-desktop-updates/25944

Let's keep this open to see if we can automate more of the process. It would be nice if there was a way to automatically rebuild the snap when a new upstream signal version is released.

**Comment by q-wertz** [comment]
Thanks a lot :+1: :rocket:

**Comment by AlanGriffiths** [comment]
> It would be nice if there was a way to automatically rebuild the snap when a new upstream signal version is released.

We do something similar in Mir - i.e. rebuild snaps when Mir releases (or a PR is merged to master). Maybe there's something you can reuse:

https://github.com/MirServer/mir/blob/master/.github/workflows/snaps.yml

https://github.com/MirServer/mir/blob/master/tools/process_snaps.py

**Comment by mdehollander** [comment]
Hereby a ping that there have been several new releases for signal-desktop. The current version is v5.25.1. Can someone give the version of the snap a bump? Thanks!

**Comment by Fuseteam** [comment]
@mdehollander might be better to leave a reply on https://forum.snapcraft.io/t/testing-signal-desktop-updates/25944/21
something should be done about faster adoption tho like alan griffiths proposed

**Comment by q-wertz** [comment]
According to the [Snapcraft Forum](https://forum.snapcraft.io/t/the-snapcrafters-need-your-help/27364) @galgalesh is looking for maintainers for signal-desktop. 

Looks like he does not have enough time to keep it maintained and might be in the process of transferring it.

**Comment by mdehollander** [comment]
I have posted a ping on the forum.

Regarding the autoupdate, here are some links to the bioconda project that has an autobump system with a bot and also uses circleci to build packages:
  - [Bioconda docs](https://bioconda.github.io/developer/_autosummary/bioconda_utils.autobump.html)
  - [Merge request on github](https://github.com/bioconda/bioconda-recipes/pulls?q=is%3Apr+is%3Aclosed)
  - [Autobump code](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/autobump.py)

A similar process can be maybe used for snap packages? I think it would really help the project if packages are more frequently updated. I often do not find the latest version of a tool as snap and many snaps are not updated or unmaintained. Not a good sign! For the bioconda project the autobump feature together with PRs in Github and CI builds really helped to keep a constant update flow going :)

Are automatic updates something snapcrafters can initiate, or is this something that should happen at the canonical/snap side?

**Comment by Fuseteam** [comment]
Updates by the community is the whole point of the snapcrafters group fwiw, if you want why not apply?
It is the packager that pushes the update not canonical think of the snap store like you do the play store

Also also we also got and suggestion for "autobump" here: https://github.com/snapcrafters/signal-desktop/issues/58#issuecomment-895875164

**Comment by mdehollander** [comment]
> 

Yes, I agree that the snapcrafters is great for this. But manually maintaining things seems to be a bottleneck, if I see how many not updates snaps there are. But this topic goes a bit beyond the signal package I guess, it is more general. Something like Alan proposed or an approach I linked could be helpful to automate things.

I see that if the github repo is updated, the CI is triggered: https://snapcraft.io/build So if there would be a bot, [similar to the flathubbot I see now as well](https://github.com/flathub/org.signal.Signal/commits/master), it would be possible to autobump snap packages, or not?

**Comment by Fuseteam** [comment]
if some of snaps are not as updated as you like, that likely means the maintainer of the snap needs help if you ask me.
either way it was already mentioned the maintainer of the signal snap needs help, and a couple of solutions have been proposed. so i guess @someone should make a pr implementing one of those proposals
