### ISSUE TITLE
Missing font in file dialog

### ISSUE THREAD

**Issue by mgajda** [snapcrafters/signal-desktop#59]
When composing a message, I pressed "+" button, and got the following view.

![Missing fonts in file dialog](https://i.imgur.com/Wn3Q3yu.png)

Even after installing "Caracteres L1" font into `~/.local/share/fonts` the problem persists.
How to fix it?

Signal snap versiron: 5.7.1  2021-07-06
Ubuntu version: Hirsute (21.04)

**Comment by der-eismann** [comment]
Same here on Fedora 35. Found [this issue](https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/98) on the snap forum. Maybe #50 helps.

**Comment by merlijn-sebrechts** [comment]
We switched to core22. That should make stuff a bit more robust. I'm closing this now, feel free to reopen if this still exists in the latest version!
