### ISSUE TITLE
Build on armv7hf/arm64?

### ISSUE THREAD

**Issue by mikefedyk** [snapcrafters/signal-desktop#6]
I have a Acer Chromebook r13 and I'm trying to use signal desktop on it.

Currently the Android app doesn't work on tablets, and it seems that ChromeOS falls under this category.

Also their .deb package for xenial is only built for amd64.  Also, considering how reluctant they are to build for x86-32, asking there seems unlikely to produce results anytime soon.  Also, armv7 compatibility with raspberry pi brings in complications with older board versions that don't support HF, so I'm not asking for that.  armv7hf may be an ok compromise.  It won't work on old RPI boards, but anything armv7hf compatible and up will.

Any chance the snap can be built for armv7hf and/or arm64?

**Comment by popey** [comment]
Upstream only build an amd64 deb and we currently consume that to build the snap. Unless upstream plan to support other architectures, I think it's not within our scope. It may well be possible to build from source using the upstream build instructions, but knowing from personal experience, building the amd64 package binaries are enough work as it is, adding more architectures is extra work for little return IMO.
