### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by wwp** [snapcrafters/signal-desktop#60]
Hi,
there no sound when installed on CentOS 7 (5.12.x/5.13.x), and I think it's was working before (when?): notifications make no sound, playing audio messages make no sound, etc.
In output, I see this:
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM plug:default
(/usr/share/alsa/alsa.conf exists and sound works as expected on desktop in other apps).

**Comment by galgalesh** [comment]
Hey @wwp 

Can you check if the sound plugs are still connected with `snap connections signal-desktop`?

I don't have much experience with CentOS. Would it be possible for you to provide us with a VM which reproduces the issue?

**Comment by wwp** [comment]
Interface                 Plug                            Slot                             Notes
audio-playback            signal-desktop:audio-playback   :audio-playback                  -
audio-record              signal-desktop:audio-record     :audio-record                    -
[..]
content[sound-themes]     signal-desktop:sound-themes     gtk-common-themes:sound-themes   -
[..]

Seems they are still plugged in.
Providing a VM.. not in short delays, I'm afraid. What VM format would you use?

**Comment by galgalesh** [comment]
Ok, that seems to be in order.


In OVA format from VirtualBox or VMware if that's possible. Just let us know which software you used to create it and we should be able to use it ourselves.

If anyone else wants to take a shot at it, feel free to help out. I currently don't have the bandwidth do try to replicate it myself.

**Comment by galgalesh** [comment]
Closing this issue for lack of response. Let me know if you're still having this issue.
