### ISSUE TITLE
Messages are displayed "New message" but do not appear when clicking on chat.

### ISSUE THREAD

**Issue by Lukas2112** [snapcrafters/signal-desktop#62]
I now have the problem under Ubuntu 20.04. LTS that new messages are displayed but are not displayed when clicking on the chat or are inserted into an existing chat history.

**Comment by galgalesh** [comment]
Are you still having this issue with the latest version of the snap? This was probably a bug in Signal itself which should be fixed by now.

**Comment by galgalesh** [comment]
Ok, I'll close this message for now. If anyone else has this problem, please let us know.
