### ISSUE TITLE
 GUI in signal-desktop snap not working

### ISSUE THREAD

**Issue by RomBuch** [snapcrafters/signal-desktop#63]
System: Ubuntu 21.10
Signal Desktop Version: 5.22.0

I use signal-desktop from snap package in Ubuntu 21.10.

Generally, I can use the app, but the GUI does not work well when "popup elemens" are created.

Examples are:

Main Menu -> Window
Settings -> Design -> Drop down menu
Voice call -> Pop up to give microphone permission
Mark text -> right klick text e.g. for copy

Signal will often freeze when this graphic bug takes place.

See attached screenshots.
![Bildschirmfoto von 2021-11-06 20-25-59](https://user-images.githubusercontent.com/19626851/140642873-344e490a-f722-4277-b217-a0b286e9595e.png)
![Bildschirmfoto von 2021-11-06 20-26-15](https://user-images.githubusercontent.com/19626851/140642874-6b6e48ed-dabf-48a1-bd2b-0375b5309641.png)
![image](https://user-images.githubusercontent.com/19626851/140642875-9f2d561f-8efc-4a3b-8491-dadb1c1a224c.png)

**Comment by galgalesh** [comment]
I cannot reproduce this issue on Ubuntu 22.04. Are you still having this issue currently?

**Comment by RomBuch** [comment]
Hi galgalesh.

Sorry for the late reply. I just checked: it works with Ubuntu 20.04 and signal-desktop version 5.59.0.

I can open menus or select entries from drop-down menu in settings. There are no gui bugs anymore as shown above and signal does not freeze. :) So, it seems to have been fixed somehow.

I'll just close.
