### ISSUE TITLE
[Bug]: Context menus are not rendered on hyperlink right clicks

### ISSUE THREAD

**Issue by tdimitrov** [snapcrafters/signal-desktop#65]
### What happened?

When you receive a message with a hyperlink and try to right click it no context menu is rendered:
![image](https://user-images.githubusercontent.com/610755/176426538-85cd5680-fe1a-4a58-8f4d-bc6d92da6c6d.png)

Sometimes signal becomes unresponsive after this action - it takes a few seconds for the empty context menu to show up.

### What should have happened?

I expect to see a context menu with copy, etc commands.

### Output of `snap info $snap_name`

```shell
name:      signal-desktop
summary:   Signal Desktop
publisher: Snapcrafters
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com/snapcrafters/signal-desktop/issues
license:   unset
description: |
  Private messaging from your desktop.
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: 7 days ago, at 17:25 EEST
channels:
  latest/stable:    5.46.0 2022-06-22 (388) 180MB -
  latest/candidate: ↑                             
  latest/beta:      ↑                             
  latest/edge:      5.46.0 2022-06-22 (388) 180MB -
installed:          5.46.0            (388) 180MB -
```

### Output of `snap connections $snap_name`

```shell
Interface                 Plug                            Slot                             Notes
audio-playback            signal-desktop:audio-playback   :audio-playback                  -
audio-record              signal-desktop:audio-record     :audio-record                    -
browser-support           signal-desktop:browser-support  :browser-support                 -
camera                    signal-desktop:camera           :camera                          -
content[gnome-3-28-1804]  signal-desktop:gnome-3-28-1804  gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     signal-desktop:gtk-3-themes     gtk-common-themes:gtk-3-themes   -
content[icon-themes]      signal-desktop:icon-themes      gtk-common-themes:icon-themes    -
content[sound-themes]     signal-desktop:sound-themes     gtk-common-themes:sound-themes   -
desktop                   signal-desktop:desktop          :desktop                         -
desktop-legacy            signal-desktop:desktop-legacy   :desktop-legacy                  -
gsettings                 signal-desktop:gsettings        :gsettings                       -
home                      signal-desktop:home             :home                            -
network                   signal-desktop:network          :network                         -
opengl                    signal-desktop:opengl           :opengl                          -
removable-media           signal-desktop:removable-media  -                                -
unity7                    signal-desktop:unity7           :unity7                          -
wayland                   signal-desktop:wayland          :wayland                         -
x11                       signal-desktop:x11              :x11
```

### Output of `snap version`

```shell
snap    2.56
snapd   2.56
series  16
ubuntu  22.04
kernel  5.15.0-40-generic
```

**Comment by galgalesh** [comment]
I cannot reproduce this issue: 

![image](https://user-images.githubusercontent.com/1492981/176778067-bbb30c56-b78a-4a3b-9470-b5cfc72e2235.png)

Same OS and version, both on Xorg and Wayland.

Have you tried rebooting? Does the problem persist afterwards? Do you have it with every URL?

**Comment by tdimitrov** [comment]
Very strange. The problem persists after reboot, on my new laptop and since at least two ubuntu releases.
Normal context menus are rendered just fine. E.g.:
![image](https://user-images.githubusercontent.com/610755/176853878-a9c4ba79-d427-423b-a7b1-80decc463f0b.png)
However right click on http or https links renders an empty menu.

Is there any cache or other data of the app which I can wipe? Maybe it's something else related to my environment.

**Comment by galgalesh** [comment]
You can run `snap remove --purge signal-desktop` and then again `snap install signal-desktop` to do a complete wipe and re-install.

**Comment by tdimitrov** [comment]
Didn't help. I can try tonight to boot a live CD, install signal and link it with my account.

The weird thing is that context menus are not rendered in one other snap app too. It affects all context menus there though.

**Comment by galgalesh** [comment]
Which app specifically?

**Comment by tdimitrov** [comment]
> Which app specifically?

Skype. Right clicking a message renders empty context menu and app becomes unresponsive. 
It's somewhat similar, but in Skype it happens no matter if a link or just text is right clicked.

**Comment by tdimitrov** [comment]
It must be something with my setup because the snap works just fine in a vanilla ubuntu 22.04 VM.
