### ISSUE TITLE
Signal can't be re-run if one of the standard HOME dirs (e.g. ~/Documents) is a symlink

### ISSUE THREAD

**Issue by aplaice** [snapcrafters/signal-desktop#7]
Just to clarify — this isn't about the snap not having access to these directories if they're symlinks, but that `signal-desktop` itself completely fails to run more than once if they're symlinks.

## To reproduce

(On Ubuntu 16.04.)

1. Make `~/Documents` a symlink and run `signal-desktop` for the first time.

```shell
mv Documents Documents_back
EXTERNAL_DOCUMENTS_DIRECTORY=/media/aplaice/drive/Documents/
mkdir -p "$EXTERNAL_DOCUMENTS_DIRECTORY"
ln -s "$EXTERNAL_DOCUMENTS_DIRECTORY" Documents
# sudo snap install signal-desktop
snap run signal-desktop # or just signal-desktop
```

Quit `signal-desktop` (with or without doing anything in the application itself).

2. Try running `signal-desktop` a second time.
```shell
snap run signal-desktop
```

## Expected behaviour

`signal-desktop` starts both times.

## Actual behaviour

`signal-desktop` starts correctly the first time, but fails silently (without any graphical or terminal feedback, but with an exit code — obtained with `$?` — of 1) the second time.

## Further details

Cleaning out `~/snap/signal-desktop/` allows you to run `signal-desktop` once more, "resetting the counter". In particular, removing both `~/snap/signal-desktop/current/.config/user-dirs.dirs` and all the symlinks to the "HOME" directories (`~/snap/signal-desktop/current/Documents/` etc.) is sufficient to "reset the counter". Obviously, since these are regenerated every time `signal-desktop` is run, this isn't a solution.

## Speculation

Interestingly, if one "disconnects" the home directory:

```shell
sudo snap disconnect signal-desktop:home
```

so that `signal-desktop` doesn't have read/write access to the home directory, `signal-desktop` will still fail exactly as above (if `~/Documents/` is a symlink). However, if `~/Documents/` and the other XDG user dirs are not symlinks, (but `:home` is still "disconnected"), `signal-desktop` will run completely fine. This suggests (but I have extremely little experience with `snap`, so this might be a completely false lead) that the bug isn't due to `signal-desktop` itself, but due to some of its `snap` helpers/wrappers.

If the symlink is into one of the standard XDG user dirs, e.g.

```shell
ln -s  ~/Videos/Documents ~/Documents
```

obviously if `~/Videos` itself isn't a symlink, the bug also does not occur — `signal-desktop` (re-)runs correctly.

## Ubuntu 18.04

On Ubuntu Mate 18.04, if `~/Documents` is a symlink, `signal-desktop` fails to start even the first time. (Otherwise it works fine.) I have not had time to test this with Ubuntu GNOME 18.04.

**Comment by ckruse** [comment]
oh wtf, this explains my problems with this snap. Signal just stopped starting some time ago.

**Comment by aplaice** [comment]
FWIW I have an extremely hacky workaround, that's been successfully working for me for the past couple of weeks. It requires at least one of the standard xdg-user-dirs being in its standard location and *not* being a symlink. For definiteness, let's take `~/Downloads` as the directory that's not a symlink (but it could be one of the others, though probably not `Public` or `Templates`).

1. Edit `~/snap/signal-desktop/current/.config/user-dirs.dirs` replacing the locations of the symlinked directories with the location of the directory that isn't a symlink. For example, replace what would normally be:

    XDG_DOCUMENTS_DIR="$HOME/Documents"

with:

    XDG_DOCUMENTS_DIR="$HOME/Downloads"

2. Remove all the currently existing non-hidden symlinks in `~/snap/signal-desktop/current/`.

3. Run `signal-desktop`.

(I hope that I haven't forgotten about any steps, since I did it a while ago.)

The point is to cheat whatever apparmor (?) confinement policies are there, by passing a set of paths that can be definitely accessed, by whatever it is that needs to access the home dirs.

**Comment by merlijn-sebrechts** [comment]
This is fixed in the latest version. Thanks for reporting this!
