### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abedholme** [snapcrafters/signal-desktop#78]
### What happened?

Can't install signal desktop on ubuntu. In snap store, I click install, and a message pops up that  says "Cannot install Signal Desktop, unable to perform the following tasks:" but then it doesn't list any tasks. 

![image](https://user-images.githubusercontent.com/14852850/205070603-e18a13e5-22f6-4c74-8a33-47c9e8abadcf.png)

### What should have happened?

I would have expected signal to be installed.

Also, note that when I try to install in terminal with snap install signal-desktop it tells me:
error: cannot perform the following tasks:
- Mount snap "signal-desktop" (405) (cannot validate license "AGPL-3.0-only": unknown license: AGPL-3.0-only)

I tried googling AGPL-3.0 licenses but it appears to be some sort of haskell programming thing and is well out of my wheelhouse, so decided to open this bug. 

### Output of `snap info $snap_name`

```shell
name:      signal-desktop
summary:   Private messaging from your desktop.
publisher: Snapcrafters
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com/snapcrafters/signal-desktop/issues
license:   AGPL-3.0-only
description: |
  Private messaging from your desktop.
  
  To use the Signal desktop app, Signal must first be installed on your phone.
  
  **Are you having issues?**
  
  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
snap-id: r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
channels:
  latest/stable:    5.63.1 2022-11-20 (405) 197MB -
  latest/candidate: ↑                             
  latest/beta:      5.62.0 2022-11-24 (400) 192MB -
  latest/edge:      6.0.0  2022-11-30 (406) 196MB -
```

### Output of `snap connections $snap_name`

```shell
error: snap "signal-desktop" not found
```

### Output of `snap version`

```shell
snap    2.48.2.1
snapd   2.48.2.1
series  16
ubuntu  20.04
kernel  5.15.0-56-generic
```

### Relevant log output

```shell
none
```

### Teminal output of app

```shell
signal-desktop: command not found
```

**Comment by merlijn-sebrechts** [comment]
This seems to be caused by the fact that you're using an outdated version of `snapd`. It doesn't understand the license of this package yet. Can you try to update all packages to the latest version and try again? (`sudo apt update; sudo apt upgrade; sudo snap refresh`)

**Comment by abedholme** [comment]
this worked. gosh what a simple fix. Sorry for the silly bug and thanks for the quick reply.
