### ISSUE TITLE
Attempting to download media file crashes app in Ubuntu 18.04 Bionic 

### ISSUE THREAD

**Issue by padames** [snapcrafters/signal-desktop#9]
I raised this issue with the signal-desktop developers and with their help it was concluded this was due at least to an icon missing from the Adwaita icon set. 
Since this is a snap packaging issue it could be more suitable addressed by the snap building team.

See the now-closed bug report:
[Signal-Desktop, issue 3447](https://github.com/signalapp/Signal-Desktop/issues/3447)

The error message when running `signal-desktop` from the command line is:

> (signal-desktop:17857): Gtk-WARNING **: 07:58:28.999: Could not load a pixbuf from icon theme.

> This may indicate that pixbuf loaders or the mime database could not be found.

> **

> Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error 
== NULL): Failed to load /snap/signal-desktop/115/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Aborted (core dumped)

**Comment by Djiock** [comment]
Hi !
Same issue here, on Ubuntu 19.04 :

(signal-desktop:5429): GdkPixbuf-WARNING **: 23:01:57.986: Cannot open pixbuf loader module file '/home/julien/snap/signal-desktop/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/julien/snap/signal-desktop/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/signal-desktop/151/data-dir/icons/Yaru/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Abandon (core dumped)

Didn't find how to run gdk-pixbuf-query-loaders, not sure if it's relevant.

**Comment by padames** [comment]
It is working all correct for me now. I just now realized that the fix must have happened recently!
